name = "xi-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail"
database_id = ""    # 替换为你的 D1 database_id，通过 `npx wrangler d1 create cloud-mail` 获取

[[kv_namespaces]]
binding = "kv"
id = ""    # 替换为你的 KV namespace id，通过 `npx wrangler kv namespace create kv` 获取

[[r2_buckets]]
binding = "r2"
bucket_name = "cloud-mail"    # 替换为你的 R2 bucket 名称

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


[vars]
orm_log = false
domain = ["example.com"]					#邮件域名，可配置多个，示例: ["example1.com","example2.com"]
admin = "admin@example.com"				#管理员邮箱
jwt_secret = "your-jwt-secret-here"		#jwt令牌密钥，填一串随机字符串

[build]
command = "pnpm --prefix ../mail-view install && pnpm --prefix ../mail-view run build"
